# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel egg
        sudo apt-get update
        sudo apt-get install libgtk-3-dev
        sudo apt-get install libgirepository1.0-dev gcc libcairo2-dev pkg-config gir1.2-gtk-3.0
        sudo apt-get install gir1.2-gtk-3.0 gir1.2-webkit2-4.0
        sudo apt-get install python-gi python-gi-cairo python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0
        sudo apt-get install gtk+-3.0
        sudo apt-get install webkit2gtk-4.0
        pkg-config --cflags gtk+-3.0 webkit2gtk-4.0
        pkg-config --libs gtk+-3.0 webkit2gtk-4.0
    - name: Build
      run: |
        python setup.py sdist
  
  upload:
  
      name: Display results
      needs: build
      runs-on: ubuntu-latest
      steps:
      - shell: bash
        run: |
          value=`ls`
          valu=`ls dist`
          echo The result is $value
          echo The result is $valu
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: dist/*

